module:
    hugoVersion:
        extended: true
        min: "0.87.0"
baseURL: http://localhost:1313/
title: OneLou
keywords: OneLou
description: OneLou
paginate: 10
hasCJKLanguage: true
languageCode: 'en-us'
theme: # "hugo-theme-onelou"
params:
  opengraph:
    github: 'https://github.com/OehlingerP'
    twitter: 'https://twitter.com/OehlingerP'
    facebook: 'https://facebook.com/peter.ohlinger'
    linkedin: 'https://www.linkedin.com/in/peter-oehlinger'
  footer:
    hidePowered: true # Powered by Hugo & theme OneLou
    # beian: # ICP备案号
    gongan:
      # code: 公安备案号XXXX
      # txt: 京公网安备XXXX号
    since: 2022
    copyright:
  prefix:
    h2: ""
    h3: ""
menu:
  navs:
    - name: Publications
      params:
        img: /img/crane-circle-bw.png
      url: /publications
      weight: 1
    - name: Research
      params:
        img: /img/crane-circle-bw.png
      url: /post/
      weight: 2
    - name: Projects
      params:
        img: /img/neurons-circle.png
      url: /projects/
      weight: 3
    - name: About
      params:
        img: /img/ship-circle-bw.png
      url: /about
      weight: 4
